apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mazibinfo/react-argocd-ci-cd.git
    targetRevision: main
    path: react-app-helm
    helm:
      valueFiles:
        - values.yaml
        - values-stage.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: react-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
